<a href="https://colab.research.google.com/github/umar0921/titanic/blob/main/Houseprice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("train.csv", index_col = "Id")

In [3]:
df.head()

    MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                    ...
1           60       RL         65.0  ...        WD        Normal    208500
2           20       RL         80.0  ...        WD        Normal    181500
3           60       RL         68.0  ...        WD        Normal    223500
4           70       RL         60.0  ...        WD       Abnorml    140000
5           60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [4]:
df.tail()

      MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                      ...
1456          60       RL         62.0  ...        WD        Normal    175000
1457          20       RL         85.0  ...        WD        Normal    210000
1458          70       RL         66.0  ...        WD        Normal    266500
1459          20       RL         68.0  ...        WD        Normal    142125
1460          20       RL         75.0  ...        WD        Normal    147500

[5 rows x 80 columns]

In [5]:
df.shape

(1460, 80)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 923.9+ KB

In [7]:
df.describe()

        MSSubClass  LotFrontage  ...       YrSold      SalePrice
count  1460.000000  1201.000000  ...  1460.000000    1460.000000
mean     56.897260    70.049958  ...  2007.815753  180921.195890
std      42.300571    24.284752  ...     1.328095   79442.502883
min      20.000000    21.000000  ...  2006.000000   34900.000000
25%      20.000000    59.000000  ...  2007.000000  129975.000000
50%      50.000000    69.000000  ...  2008.000000  163000.000000
75%      70.000000    80.000000  ...  2009.000000  214000.000000
max     190.000000   313.000000  ...  2010.000000  755000.000000

[8 rows x 37 columns]

In [8]:
df_cont = df.select_dtypes(include = ["int64", "float64"])

In [9]:
df_cont.shape

(1460, 37)

In [10]:
df_cat = df.select_dtypes(include = ["object"])

In [11]:
df_cat.shape

(1460, 43)

In [12]:
#df_cont.hist(bins = 50, figsize = (30, 15))
#plt.show()

In [13]:
#for i in df_cat.columns:
#  sns.displot(data = df_cat, x = i)

In [14]:
df_cont.isnull().sum()

MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [15]:
df_cat.isnull().sum()

MSZoning            0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinType2       38
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
KitchenQual         0
Functional          0
FireplaceQu       690
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
PavedDrive          0
PoolQC           1453
Fence            1179
MiscFeature      1406
SaleType            0
SaleCondition       0
dtype: int64

In [16]:
for i in df.columns:
  if "Yr" in i:
    print(i)

GarageYrBlt
YrSold

In [17]:
from datetime import datetime

In [18]:
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(df["GarageYrBlt"].median())

In [19]:
df["GarageYrBlt"] = datetime.now().year - df["GarageYrBlt"]

In [20]:
df["YrSold"] = datetime.now().year - df["YrSold"]

In [21]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].median())
df["MasVnrArea"] = df["MasVnrArea"].fillna(df["MasVnrArea"].median())

In [22]:
df["MasVnrType"] = df["MasVnrType"].fillna(df["MasVnrType"].mode()[0])
df["BsmtQual"] = df["BsmtQual"].fillna(df["BsmtQual"].mode()[0])
df["BsmtCond"] = df["BsmtCond"].fillna(df["BsmtCond"].mode()[0])
df["BsmtExposure"] = df["BsmtExposure"].fillna(df["BsmtExposure"].mode()[0])
df["BsmtFinType1"] = df["BsmtFinType1"].fillna(df["BsmtFinType1"].mode()[0])
df["BsmtFinType2"] = df["BsmtFinType2"].fillna(df["BsmtFinType2"].mode()[0])
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])
df["GarageType"] = df["GarageType"].fillna(df["GarageType"].mode()[0])
df["GarageFinish"] = df["GarageFinish"].fillna(df["GarageFinish"].mode()[0])
df["GarageQual"] = df["GarageQual"].fillna(df["GarageQual"].mode()[0])
df["GarageCond"] = df["GarageCond"].fillna(df["GarageCond"].mode()[0])

In [23]:
df["Alley"] = df["Alley"].fillna("others_alley")
df["FireplaceQu"] = df["FireplaceQu"].fillna("others_fireplacequ")
df["PoolQC"] = df["PoolQC"].fillna("others_poolqc")
df["Fence"] = df["Fence"].fillna("others_fence")
df["MiscFeature"] = df["MiscFeature"].fillna("others_miscfeature")

In [24]:
df.isnull().sum()

MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 80, dtype: int64

In [25]:
y = df["SalePrice"]

In [26]:
X = df.drop("SalePrice", axis = 1)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y,train_size=0.8, test_size=0.2, random_state=0)

In [28]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse = False)

In [29]:
df_cat_train = X_train[df_cat.columns]
enc_cat_train = pd.DataFrame(enc.fit_transform(df_cat_train))
enc_cat_train.index = X_train.index
df_num_train = X_train.drop(df_cat_train, axis = 1)
X_train = pd.concat([df_num_train, enc_cat_train], axis = 1)

In [30]:
df_cat_valid = X_valid[df_cat.columns]
enc_cat_valid = pd.DataFrame(enc.transform(df_cat_valid))
enc_cat_valid.index = X_valid.index
df_num_valid = X_valid.drop(df_cat_valid, axis = 1)
X_valid = pd.concat([df_num_valid, enc_cat_valid], axis = 1)

In [31]:
from xgboost import XGBRegressor

In [32]:
model1 = XGBRegressor()

In [33]:
model1.fit(X_train, y_train)

[15:44:00] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [34]:
y_pred1 = model1.predict(X_valid)

In [35]:
from sklearn.metrics import mean_squared_log_error

In [36]:
mean_squared_log_error(y_valid, y_pred1)

0.01700387891996013

Test Data

In [37]:
df_test = pd.read_csv("test.csv", index_col = "Id")

In [38]:
df_cat_test = df_test.select_dtypes(include = ["object"])

In [39]:
df_cont_test = df_test.select_dtypes(include = ["int64", "float64"])

In [40]:
df_cont_test.isnull().sum()

MSSubClass         0
LotFrontage      227
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea        15
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       2
BsmtHalfBath       2
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       78
GarageCars         1
GarageArea         1
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [41]:
df_cat_test.isnull().sum()

MSZoning            4
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType         16
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinType2       42
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
KitchenQual         1
Functional          2
FireplaceQu       730
GarageType         76
GarageFinish       78
GarageQual         78
GarageCond         78
PavedDrive          0
PoolQC           1456
Fence            1169
MiscFeature      1408
SaleType            1
SaleCondition       0
dtype: int64

In [42]:
df_test["GarageYrBlt"] = df_test["GarageYrBlt"].fillna(df["GarageYrBlt"].median())

In [43]:
df_test["GarageYrBlt"] = datetime.now().year - df_test["GarageYrBlt"]

In [44]:
df_test["YrSold"] = datetime.now().year - df_test["YrSold"]

In [45]:
df_test["LotFrontage"] = df_test["LotFrontage"].fillna(df["LotFrontage"].median())
df_test["MasVnrArea"] = df_test["MasVnrArea"].fillna(df["MasVnrArea"].median())
df_test["BsmtFinSF1"] = df_test["BsmtFinSF1"].fillna(df["BsmtFinSF1"].median())
df_test["BsmtFinSF2"] = df_test["BsmtFinSF2"].fillna(df["BsmtFinSF2"].median())
df_test["BsmtUnfSF"] = df_test["BsmtUnfSF"].fillna(df["BsmtUnfSF"].median())
df_test["TotalBsmtSF"] = df_test["TotalBsmtSF"].fillna(df["TotalBsmtSF"].median())
df_test["BsmtFullBath"] = df_test["BsmtFullBath"].fillna(df["BsmtFullBath"].median())
df_test["BsmtHalfBath"] = df_test["BsmtHalfBath"].fillna(df["BsmtHalfBath"].median())
df_test["GarageCars"] = df_test["GarageCars"].fillna(df["GarageCars"].median())
df_test["GarageArea"] = df_test["GarageArea"].fillna(df["GarageArea"].median())

In [46]:
df_test["MSZoning"] = df_test["MSZoning"].fillna(df["MSZoning"].mode()[0])
df_test["Utilities"] = df_test["Utilities"].fillna(df["Utilities"].mode()[0])
df_test["Exterior1st"] = df_test["Exterior1st"].fillna(df["Exterior1st"].mode()[0])
df_test["Exterior2nd"] = df_test["Exterior2nd"].fillna(df["Exterior2nd"].mode()[0])
df_test["MasVnrType"] = df_test["MasVnrType"].fillna(df["MasVnrType"].mode()[0])
df_test["BsmtQual"] = df_test["BsmtQual"].fillna(df["BsmtQual"].mode()[0])
df_test["BsmtCond"] = df_test["BsmtCond"].fillna(df["BsmtCond"].mode()[0])
df_test["BsmtExposure"] = df_test["BsmtExposure"].fillna(df["BsmtExposure"].mode()[0])
df_test["BsmtFinType1"] = df_test["BsmtFinType1"].fillna(df["BsmtFinType1"].mode()[0])
df_test["BsmtFinType2"] = df_test["BsmtFinType2"].fillna(df["BsmtFinType2"].mode()[0])
df_test["KitchenQual"] = df_test["KitchenQual"].fillna(df["KitchenQual"].mode()[0])
df_test["Functional"] = df_test["Functional"].fillna(df["Functional"].mode()[0])
df_test["GarageType"] = df_test["GarageType"].fillna(df["GarageType"].mode()[0])
df_test["GarageFinish"] = df_test["GarageFinish"].fillna(df["GarageFinish"].mode()[0])
df_test["GarageQual"] = df_test["GarageQual"].fillna(df["GarageQual"].mode()[0])
df_test["GarageCond"] = df_test["GarageCond"].fillna(df["GarageCond"].mode()[0])
df_test["SaleType"] = df_test["SaleType"].fillna(df["SaleType"].mode()[0])

In [47]:
df_test["Alley"] = df_test["Alley"].fillna("others_alley")
df_test["FireplaceQu"] = df_test["FireplaceQu"].fillna("others_fireplacequ")
df_test["PoolQC"] = df_test["PoolQC"].fillna("others_poolqc")
df_test["Fence"] = df_test["Fence"].fillna("others_fence")
df_test["MiscFeature"] = df_test["MiscFeature"].fillna("others_miscfeature")

In [48]:
df_cat_test = df_test.select_dtypes(include = ["object"])

In [49]:
df_cont_test = df_test.select_dtypes(include = ["int64", "float64"])

In [50]:
df_cat_test = df_test[df_cat_test.columns]
enc_cat_test = pd.DataFrame(enc.transform(df_cat_test))
enc_cat_test.index = df_test.index
df_num_test = df_test.drop(df_cat_test, axis = 1)
X_test = pd.concat([df_num_test, enc_cat_test], axis = 1)

In [52]:
y_pred_test = model1.predict(X_test)

In [53]:
a = pd.DataFrame({"SalePrice": y_pred_test}, index = X_test.index)

In [54]:
subm = a.to_csv("subm.csv")